### ISSUE TITLE
안녕하세요!

### ISSUE THREAD

**Issue by SoJeonghu** [devmemory/kakaomap_webview#1]
안녕하세요 덕분에 플러터에서 카카오  웹뷰를 잘쓰고있습니다

다름 아니라 혹시 지도의 레벨을 상황에 따라 바꾸고 가능할까요?

**Comment by devmemory** [comment]
현재는 zoom controller만 만들어 놨는데, 아마도 지도 위젯 외부에서 레벨을 변경하고 싶으신거로 이해 했고
그 경우에는 웹뷰의 evaluateJavascript 메소드를 사용해서 map.setLevel(숫자) 이런 형태로 하면 될것 같습니다
추가로 메소드 몇개 만들어서 업데이트해 드리겠습니다
