### ISSUE TITLE
Uncaught TypeError: kakao.maps.LatLng is not a constructor 이슈

### ISSUE THREAD

**Issue by ehog0613-doubled** [devmemory/kakaomap_webview#15]
안녕하세요
안드로이드에서 KakaoMapView 붙이니 

Uncaught TypeError: kakao.maps.LatLng is not a constructor

이슈가 생깁니다. 혹시 방법이 있나요?

**Comment by devmemory** [comment]
안녕하세요

에러 내용 보면 script load가 안된거 같은데

제가 만들어놓은 예제에서 해당 문제발생이 안되어서

구현 코드 확인해봐야될거 같습니다

**Comment by ehog0613-doubled** [comment]
이리저리 시도해봤는데 안돼서 KakaoMapView 사용안하고 webview 에 custom html load 했습니다. 
url 에 'autoload=true' 삭제하니 되네요. :)
참고로 테스트 폰은 S20 울트라, 안드로이드 버전 12 였습니다.
