### ISSUE TITLE
안녕하세요? 문의합니다

### ISSUE THREAD

**Issue by chinzorigts** [devmemory/kakaomap_webview#4]
제가 KakaoMapView 안에서 cameraIdle event-로 카메라 움직이면 다른 버튼 스테이트를 바꿔려고 하는데 setState(){} 호출하면 맵 Widget 까박거리거든요. 이거를 어떻게 해결 할 수 있을까요?

**Comment by devmemory** [comment]
따로 상태관리 패키지를 사용하시거나 StreamBuilder혹은 ValueListenableBuilder를 사용하시면 될 것 같습니다
