### ISSUE TITLE
웹뷰 새로고침은 가능한가요?

### ISSUE THREAD

**Issue by gamcho3** [devmemory/kakaomap_webview#9]
검색어에 따라 마크를 달고 싶은데 어떻게 해야될까요 ㅠㅠ

**Comment by devmemory** [comment]
아직 테스트는 안해봤는데 테스트 해보고 말씀드리겠습니다..
일단 급하시면 데이터 변경해가면서 setState를 하는쪽으로 방향을 잡으셔야될것 같아요
